#-------------------------------
# General Site Settings
title: Pannell lab
logo: logo.svg # You can add own logo.
description: This site aims to present the Pannell Group of the University of Lausanne (Switzerland)


#-------------------------------
# Author Settings
author:
  name: Pannell lab
  image: 01.jpg
  say-hello: <strong>Pannell lab - Ecology and Evolution of Plant Sexual Systems</strong>
  bio: Current projects in the group are addressing questions concerning <strong>transitions between sexual systems</strong>. #and their implications for <strong>mating</strong>, <strong>resource allocation</strong>, <strong>demography</strong> and the evolution of the <strong>genome</strong> and <strong>transcriptome</strong>, especially <strong>sex chromosomes</strong>. Some of these are summarised under the project descriptions below. These projects use a combination of <strong>theory</strong>, <strong>wet-lab work</strong>, <strong>bioinformatics</strong>, and <strong>fieldwork</strong>. See our recent publications for further details of results from these and other projects.

#-------------------------------
# Contact links
twitter: https://twitter.com/dee_unil # Add your Twitter handle
instagram: https://www.instagram.com/unilch/?hl=fr # Add your Instagram handle
DEE website: https://www.unil.ch/dee/en/home.html
# pinterest: https://pinterest.com/ # Add your Pinterest handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
